#!/bin/sh

EXT=".php"

if [ `whoami` != "root" ]
then
    # echo "Performing sudo - I need root to edit your hosts file."
    # The above message is included if anyone wants it, but it got annoying.
    sudo $0 $*
    exit $?
fi
./get-shit-done$EXT $*
